package com.arata.yukarilauncher.feature.download.enums

import com.arata.yukarilauncher.R

/**
 * CurseForgeとModrinth両プラットフォームのカテゴリを集約した列挙型。
 * 各カテゴリが示す実際の値を記録し、リソース検索時にカテゴリを指定するために使用する。
 * カテゴリのcurseforge idまたはmodrinth idがnullの場合は、そのプラットフォームに当該カテゴリが存在しないことを意味する。
 */
enum class Category(val classify: Classify, val resNameID: Int, val curseforgeID: String?, val modrinthName: String?) {
    ALL(Classify.ALL, R.string.generic_all, null, null),

    //ModとModPackのデータソース：https://github.com/Hex-Dragon/PCL2/blob/f40a2990103ae85c34acb5d8d367ab1644aa7ca6/Plain%20Craft%20Launcher%202/Modules/Minecraft/ModComp.vb#L281
    //龍騰猫躍に感謝!!!!
    //Modカテゴリ
    MOD_WORLDGEN(Classify.MOD, R.string.category_worldgen, "406", "worldgen"),
    MOD_BIOMES(Classify.MOD, R.string.category_biomes, "407", null),
    MOD_DIMENSIONS(Classify.MOD, R.string.category_dimensions, "410", null),
    MOD_ORES_RESOURCES(Classify.MOD, R.string.category_ores_resources, "408", null),
    MOD_STRUCTURES(Classify.MOD, R.string.category_structures, "409", null),
    MOD_TECHNOLOGY(Classify.MOD, R.string.category_technology, "412", "technology"),
    MOD_ITEM_FLUID_ENERGY_TRANSPORT(Classify.MOD, R.string.category_item_fluid_energy_transport, "415", null),
    MOD_AUTOMATION(Classify.MOD, R.string.category_automation, "4843", null),
    MOD_ENERGY(Classify.MOD, R.string.category_energy, "417", null),
    MOD_REDSTONE(Classify.MOD, R.string.category_redstone, "4558", null),
    MOD_FOOD(Classify.MOD, R.string.category_food, "436", "food"),
    MOD_FARMING(Classify.MOD, R.string.category_farming, "416", null),
    MOD_GAME_MECHANICS(Classify.MOD, R.string.category_game_mechanics, null, "game-mechanics"),
    MOD_TRANSPORT(Classify.MOD, R.string.category_transport, "414", "transportation"),
    MOD_STORAGE(Classify.MOD, R.string.category_storage, "420", "storage"),
    MOD_MAGIC(Classify.MOD, R.string.category_magic, "419", "magic"),
    MOD_ADVENTURE(Classify.MOD, R.string.category_adventure, "422", "adventure"),
    MOD_DECORATION(Classify.MOD, R.string.category_decoration, "424", "decoration"),
    MOD_MOBS(Classify.MOD, R.string.category_mobs, "411", "mobs"),
    MOD_EQUIPMENT(Classify.MOD, R.string.category_equipment, "434", "equipment"),
    MOD_OPTIMIZATION(Classify.MOD, R.string.category_optimization, null, "optimization"),
    MOD_INFORMATION(Classify.MOD, R.string.category_information, "423", null),
    MOD_SOCIAL(Classify.MOD, R.string.category_social, "435", "social"),
    MOD_UTILITY(Classify.MOD, R.string.category_utility, "5191", "utility"),
    MOD_LIBRARY(Classify.MOD, R.string.category_library, "421", "library"),
    MOD_CURSED(Classify.MOD, R.string.category_cursed, null, "cursed"),
    MOD_ECONOMY(Classify.MOD, R.string.category_economy, null, "economy"),
    MOD_MANAGEMENT(Classify.MOD, R.string.category_management, null, "management"),
    MOD_MINIGAME(Classify.MOD, R.string.category_minigame, null, "minigame"),
    MOD_ADDONS(Classify.MOD, R.string.category_addons, "426", null),
    MOD_BUG_FIXES(Classify.MOD, R.string.category_bug_fixes, "6821", null),
    MOD_CREATIVE_MODE(Classify.MOD, R.string.category_creative_mode, "9026", null),
    MOD_EDUCATION(Classify.MOD, R.string.category_education, "5299", null),
    MOD_GENETICS(Classify.MOD, R.string.category_genetics, "418", null),
    MOD_HORROR(Classify.MOD, R.string.category_horror, "10775", null),
    MOD_MCREATOR(Classify.MOD, R.string.category_mcreator, "4906", null),
    MOD_MISCELLANEOUS(Classify.MOD, R.string.category_miscellaneous, "425", null),
    MOD_MODJAM(Classify.MOD, R.string.category_modjam, "8937", null),
    MOD_PERFORMANCE(Classify.MOD, R.string.category_optimization, "6814", null),
    MOD_PROCESSING(Classify.MOD, R.string.category_processing, "413", null),
    MOD_TWITCH_INTEGRATION(Classify.MOD, R.string.category_twitch_integration, "4671", null),
    MOD_AE2(Classify.MOD, R.string.category_ae2, "4545", null),
    MOD_BLOOD_MAGIC(Classify.MOD, R.string.category_blood_magic, "4485", null),
    MOD_BUILDCRAFT(Classify.MOD, R.string.category_buildcraft, "432", null),
    MOD_CRAFTTWEAKER(Classify.MOD, R.string.category_crafttweaker, "4773", null),
    MOD_CREATE(Classify.MOD, R.string.category_create, "6484", null),
    MOD_FARMERS_DELIGHT(Classify.MOD, R.string.category_farmers_delight, "10754", null),
    MOD_FORESTRY(Classify.MOD, R.string.category_forestry, "433", null),
    MOD_GALACTICRAFT(Classify.MOD, R.string.category_galacticraft, "5232", null),
    MOD_INDUSTRIAL_CRAFT(Classify.MOD, R.string.category_industrial_craft, "429", null),
    MOD_INTEGRATED_DYNAMICS(Classify.MOD, R.string.category_integrated_dynamics, "6954", null),
    MOD_KUBEJS(Classify.MOD, R.string.category_kubejs, "5314", null),
    MOD_REFINED_STORAGE(Classify.MOD, R.string.category_refined_storage, "9049", null),
    MOD_SKYBLOCK(Classify.MOD, R.string.category_skyblock, "6145", null),
    MOD_THAUMCRAFT(Classify.MOD, R.string.category_thaumcraft, "430", null),
    MOD_THERMAL_EXPANSION(Classify.MOD, R.string.category_thermal_expansion, "427", null),
    MOD_TINKERS_CONSTRUCT(Classify.MOD, R.string.category_tinkers_construct, "428", null),
    MOD_TWILIGHT_FOREST(Classify.MOD, R.string.category_twilight_forest, "7669", null),

    //ModPackカテゴリ
    MODPACK_MULTIPLAYER(Classify.MODPACK, R.string.category_multiplayer, "4484", "multiplayer"),
    MODPACK_OPTIMIZATION(Classify.MODPACK, R.string.category_optimization, null, "optimization"),
    MODPACK_CHALLENGING(Classify.MODPACK, R.string.category_challenging, "4479", "challenging"),
    MODPACK_COMBAT(Classify.MODPACK, R.string.category_combat, "4483", "combat"),
    MODPACK_QUESTS(Classify.MODPACK, R.string.category_quests, "4478", "quests"),
    MODPACK_TECHNOLOGY(Classify.MODPACK, R.string.category_technology, "4472", "technology"),
    MODPACK_MAGIC(Classify.MODPACK, R.string.category_magic, "4473", "magic"),
    MODPACK_ADVENTURE(Classify.MODPACK, R.string.category_adventure, "4475", "adventure"),
    MODPACK_KITCHEN_SINK(Classify.MODPACK, R.string.category_kitchen_sink, null, "kitchen-sink"),
    MODPACK_EXPLORATION(Classify.MODPACK, R.string.category_exploration, "4476", null),
    MODPACK_MINI_GAME(Classify.MODPACK, R.string.category_mini_game, "4477", null),
    MODPACK_SCI_FI(Classify.MODPACK, R.string.category_sci_fi, "4474", null),
    MODPACK_HORROR(Classify.MODPACK, R.string.category_horror, "7418", null),
    MODPACK_EXPERT(Classify.MODPACK, R.string.category_expert, "9243", null),
    MODPACK_RLCRAFT(Classify.MODPACK, R.string.category_rlcraft, "10683", null),
    MODPACK_SKYBLOCK(Classify.MODPACK, R.string.category_skyblock, "4736", null),
    MODPACK_VANILLA(Classify.MODPACK, R.string.category_vanilla, "5128", null),
    MODPACK_FTB(Classify.MODPACK, R.string.category_ftb, "4487", null),
    MODPACK_MAP_BASED(Classify.MODPACK, R.string.category_map_based, "4480", null),
    MODPACK_LIGHTWEIGHT(Classify.MODPACK, R.string.category_lightweight, "4481", "lightweight"),
    MODPACK_EXTRA_LARGE(Classify.MODPACK, R.string.category_extra_large, "4482", null),

    //リソースパックカテゴリ
    RP_TRADITIONAL(Classify.RESOURCE_PACK, R.string.category_traditional, "403", null),
    RP_STEAMPUNK(Classify.RESOURCE_PACK, R.string.category_steampunk, "399", null),
    RP_COMBAT(Classify.RESOURCE_PACK, R.string.category_combat, null, "combat"),
    RP_DECORATION(Classify.RESOURCE_PACK, R.string.category_decoration, null, "decoration"),
    RP_VANILLA(Classify.RESOURCE_PACK, R.string.category_vanilla, null, "vanilla-like"),
    RP_MODERN(Classify.RESOURCE_PACK, R.string.category_modern, "401", null),
    RP_PHOTO_REALISTIC(Classify.RESOURCE_PACK, R.string.category_photo_realistic, "400", "realistic"),
    RP_ANIMATED(Classify.RESOURCE_PACK, R.string.category_animated, "404", null),
    RP_MOD_SUPPORT(Classify.RESOURCE_PACK, R.string.category_mod_support, "4465", "modded"),
    RP_MISCELLANEOUS(Classify.RESOURCE_PACK, R.string.category_miscellaneous, "405", null),
    RP_8X(Classify.RESOURCE_PACK, R.string.category_8x_or_lower, null, "8x-"),
    RP_16X(Classify.RESOURCE_PACK, R.string.category_16x, "393", "16x"),
    RP_32X(Classify.RESOURCE_PACK, R.string.category_32x, "394", "32x"),
    RP_48X(Classify.RESOURCE_PACK, R.string.category_48x, null, "48x"),
    RP_64X(Classify.RESOURCE_PACK, R.string.category_64x, "395", "64x"),
    RP_128X(Classify.RESOURCE_PACK, R.string.category_128x, "396", "128x"),
    RP_256X(Classify.RESOURCE_PACK, R.string.category_256x, "397", "256x"),
    RP_512X(Classify.RESOURCE_PACK, R.string.category_512x, "398", "512x+"),
    RP_SIMPLISTIC(Classify.RESOURCE_PACK, R.string.category_simplistic, null, "simplistic"),
    RP_THEMED(Classify.RESOURCE_PACK, R.string.category_themed, null, "themed"),
    RP_TWEAKS(Classify.RESOURCE_PACK, R.string.category_tweaks, null, "tweaks"),
    RP_UTILITY(Classify.RESOURCE_PACK, R.string.category_utility, null, "utility"),
    RP_CURSED(Classify.RESOURCE_PACK, R.string.category_cursed, null, "cursed"),
    RP_FEATURE_AUDIO(Classify.RESOURCE_PACK, R.string.category_rp_feature_audio, null, "audio"),
    RP_FEATURE_BLOCKS(Classify.RESOURCE_PACK, R.string.category_rp_feature_blocks, null, "blocks"),
    RP_FEATURE_CORE_SHADERS(Classify.RESOURCE_PACK, R.string.category_rp_feature_core_shaders, null, "core-shaders"),
    RP_FEATURE_ENTITIES(Classify.RESOURCE_PACK, R.string.category_rp_feature_entities, null, "entities"),
    RP_FEATURE_ENVIRONMENT(Classify.RESOURCE_PACK, R.string.category_rp_feature_environment, null, "environment"),
    RP_FEATURE_EQUIPMENT(Classify.RESOURCE_PACK, R.string.category_rp_feature_equipment, null, "equipment"),
    RP_FEATURE_FONTS(Classify.RESOURCE_PACK, R.string.category_rp_feature_fonts, null, "fonts"),
    RP_FEATURE_GUI(Classify.RESOURCE_PACK, R.string.category_rp_feature_gui, null, "gui"),
    RP_FEATURE_ITEMS(Classify.RESOURCE_PACK, R.string.category_rp_feature_items, null, "items"),
    RP_FEATURE_LOCALE(Classify.RESOURCE_PACK, R.string.category_rp_feature_locale, null, "locale"),
    RP_FEATURE_MODELS(Classify.RESOURCE_PACK, R.string.category_rp_feature_models, null, "models"),
    RP_DATAPACKS(Classify.RESOURCE_PACK, R.string.category_datapacks, "5193", null),
    RP_FONT_PACKS(Classify.RESOURCE_PACK, R.string.category_font_packs, "5244", null),
    RP_MODJAM(Classify.RESOURCE_PACK, R.string.category_modjam, "8939", null),
    RP_MEDIEVAL(Classify.RESOURCE_PACK, R.string.category_medieval, "402", null),

    //ワールドカテゴリ
    WORLD_ADVENTURE(Classify.WORLD, R.string.category_world_adventure, "248", null),
    WORLD_SURVIVAL(Classify.WORLD, R.string.category_survival, "253", null),
    WORLD_CREATION(Classify.WORLD, R.string.category_creation, "249", null),
    WORLD_GAME_MAP(Classify.WORLD, R.string.category_game_map, "250", null),
    WORLD_MODDED_WORLD(Classify.WORLD, R.string.category_modded_world, "4464", null),
    WORLD_PARKOUR(Classify.WORLD, R.string.category_parkour, "251", null),
    WORLD_PUZZLE(Classify.WORLD, R.string.category_puzzle, "252", null),

    //シェーダーカテゴリ
    SHADER_CARTOON(Classify.SHADER_PACK, R.string.category_cartoon, null, "cartoon"),
    SHADER_CURSED(Classify.SHADER_PACK, R.string.category_cursed, null, "cursed"),
    SHADER_FANTASY(Classify.SHADER_PACK, R.string.category_fantasy, "6554", "fantasy"),
    SHADER_REALISTIC(Classify.SHADER_PACK, R.string.category_photo_realistic, "6553", "realistic"),
    SHADER_SEMI_REALISTIC(Classify.SHADER_PACK, R.string.category_semi_realistic, null, "semi-realistic"),
    SHADER_VANILLA(Classify.SHADER_PACK, R.string.category_vanilla, "6555", "vanilla-like"),
    SHADER_ATMOSPHERE(Classify.SHADER_PACK, R.string.category_atmosphere, null, "atmosphere"),
    SHADER_BLOOM(Classify.SHADER_PACK, R.string.category_bloom, null, "bloom"),
    SHADER_COLORED_LIGHTING(Classify.SHADER_PACK, R.string.category_colored_lighting, null, "colored-lighting"),
    SHADER_FOLIAGE(Classify.SHADER_PACK, R.string.category_foliage, null, "foliage"),
    SHADER_PATH_TRACING(Classify.SHADER_PACK, R.string.category_path_tracing, null, "path-tracing"),
    SHADER_PBR(Classify.SHADER_PACK, R.string.category_pbr, null, "pbr"),
    SHADER_REFLECTIONS(Classify.SHADER_PACK, R.string.category_reflections, null, "reflections"),
    SHADER_SHADOWS(Classify.SHADER_PACK, R.string.category_shadows, null, "shadows"),
    SHADER_POTATO(Classify.SHADER_PACK, R.string.category_configuration_potato, null, "potato"),
    SHADER_LOW(Classify.SHADER_PACK, R.string.category_configuration_low, null, "low"),
    SHADER_MEDIUM(Classify.SHADER_PACK, R.string.category_configuration_medium, null, "medium"),
    SHADER_HIGH(Classify.SHADER_PACK, R.string.category_configuration_high, null, "high"),
    SHADER_SCREENSHOT(Classify.SHADER_PACK, R.string.category_screenshot, null, "screenshot"),

    //シェーダーローダー
    SHADER_LOADER_IRIS(Classify.SHADER_PACK, R.string.category_shader_loader_iris, null, "iris"),
    SHADER_LOADER_OPTIFINE(Classify.SHADER_PACK, R.string.category_shader_loader_optifine, null, "optifine"),
    SHADER_LOADER_VANILLA(Classify.SHADER_PACK, R.string.category_shader_loader_vanilla, null, "vanilla"),
    SHADER_LOADER_CANVAS(Classify.SHADER_PACK, R.string.category_shader_loader_canvas, null, "canvas"),

    //環境 (Modrinth client/server)
    ENV_CLIENT(Classify.ALL, R.string.category_env_client, null, "client"),
    ENV_SERVER(Classify.ALL, R.string.category_env_server, null, "server")
}