name: Android CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  BuildDebug:
    if: startsWith(github.ref, 'refs/pull/') || github.ref_name != 'main'
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [ "all", "arm", "arm64", "x86", "x86_64" ]
      fail-fast: false

    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JRE JAR files
        run: |
          chmod +x gradlew
          mkdir out
          ./gradlew jre_lwjgl3glfw:build --no-daemon

      - name: Build Debug ${{matrix.arch}}
        run: |
          chmod +x gradlew
          ./gradlew YukariLauncher:assembleDebug -Darch=${{ matrix.arch }}

      - name: Upload Debug ${{matrix.arch}}
        uses: actions/upload-artifact@v4
        with:
          name: YukariLauncher(Debug) ${{ matrix.arch }}
          path: YukariLauncher/build/outputs/apk/debug/*
